### ISSUE TITLE
Como solucionar el borrado de paginas extra de mapeo en fork()

### ISSUE THREAD

**Issue by SW1073** [SW1073/SO2#1]
# TODO
https://github.com/SW1073/SO2/blob/6959e23d7f132bf4ebd406255b209e7380b5a884/lab/zeos/mm.c#L148
https://github.com/SW1073/SO2/blob/6959e23d7f132bf4ebd406255b209e7380b5a884/lab/zeos/mm.c#L161

Borrar esto, y poner un del_ss_pag() tras cada iteracion del bucle. Fuera del bulce, se hace el ya presente set_cr3() y a tomar viento.
Ninguna de las dos apariciones que aqui se muestran hacen falta realmente.

**Comment by Jafeth12** [comment]
ya se hará.

**Comment by Jafeth12** [comment]
no se acabó haciendo.
